### ISSUE TITLE
Direct Device Access

### ISSUE THREAD

**Issue by xloem** [jacklinquan/usb4a#3]
I've heard one can get much faster communication speed with devices if directly accessing the linux usb devices with system calls, rather than going through the android java API.   This is the approach used for libusb's android support, once the android api is used to get permission to access the device handles.  Just an idea to share, for future thoughts.

**Comment by jacklinquan** [comment]
> I've heard one can get much faster communication speed with devices if directly accessing the linux usb devices with system calls, rather than going through the android java API. This is the approach used for libusb's android support, once the android api is used to get permission to access the device handles. Just an idea to share, for future thoughts.

Hi @xloem ,
Thanks for sharing your ideas!
I'll keep this open. When I find a better and backward compatible way to implement it, I can definitely switch to it.

**Comment by jacklinquan** [comment]
Hi @xloem ,
I did not find any compatible way to implement libusb's approach.
I'll close this issue because there won't be any further activity on this issue in the near future.
