### ISSUE TITLE
data in arduino

### ISSUE THREAD

**Issue by robotixdevteam** [jacklinquan/usb4a#4]
Hi, I cannot able to get the data transfer to arduino when i try to print what it is receiving as message i get only b' '.how to solve it?

**Comment by jacklinquan** [comment]
Could you describe your test in more details?
What's the target of your test? (What do you want to achieve?)
What's your hardware and how did you connect them?
What software did you use and how did you set them up?
What's your code for testing and how did you log the result?

**Comment by robotixdevteam** [comment]
i have used your code to connect to arduino and My target is i want mobile connect to arduino and let the led to blink. I just tried to print the messages in my cmd prompt but i got only b' '.  i want to send the messages such as digitalWrite(LED_BUILTIN, HIGH); to arduino. is it possible to do so or is there any other way to do it.

**Comment by jacklinquan** [comment]
Sorry that with such little information I really can not help on it.

**Comment by robotixdevteam** [comment]
is there a way to make the led to blink just like how to they show in this link : https://www.youtube.com/watch?v=Li1KaSgdNCA
I want to replicate the same idea but through using otg cable  as the data should transfer between app and arduino

**Comment by jacklinquan** [comment]
Yes, you can try this app::
https://play.google.com/store/apps/details?id=com.quanlin.pytoolusbserial
