### ISSUE TITLE
device filter issue

### ISSUE THREAD

**Issue by robotixdevteam** [jacklinquan/usb4a#5]
hi,
I cannot able to create my app with the usb4a. when i follow the steps that you have mentioned. After creating the devicefilter.xml when i run the buildozer android debug it shows  and error that the devicefilter.xml is not found  and the some of the gradle functions are depreceated. can you help me solve it and i am running this package in vm with ubuntu20.0.
Below i am attaching my error text file.

[error.txt](https://github.com/jacklinquan/usb4a/files/8596216/error.txt)
4

**Comment by jacklinquan** [comment]
The app building tool buildozer is changed a lot.
Those instructions are outdated and need update.
I'll try to do it when I have time.

**Comment by robotixdevteam** [comment]
Hi,

Thank you for your reply.

Regards

**Comment by sidney-pauly** [comment]
@robotixdevteam and anyone else who has the same issue: 
I managed to get it working and updated the documentation in #7. Let me know if it works for you
