### ISSUE TITLE
USB Read Issues

### ISSUE THREAD

**Issue by hrnbydgn** [jacklinquan/usb4a#8]
Hi,
`
usb_device_list = usb.get_usb_device_list()
device = usb_device_list[1]
device1 = usb_device_list[1].getDeviceName()
    
while True:
    if usb.has_usb_permission(device) == True:
    while True:
        connection = mavutil.mavlink_connection(device1, port=57600, autoreconnect=True,input=True,broadcast=True)
    else:
        usb.request_usb_permission(device1)
    `
    
 I cannot read/write USB data.

**Comment by jacklinquan** [comment]
This issue has nothing to do with `usb4a` package.
`mavutil` does not support Android devices.
I will close it then.
